# Generated by Django 4.0.5 on 2022-06-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_pig', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pig',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='users.company'),
        ),
        migrations.AddField(
            model_name='pig',
            name='reproduction_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_pig.reproductionstage'),
        ),
        migrations.AddField(
            model_name='birth',
            name='pig_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_pig.pig'),
        ),
    ]
