# Generated by Django 4.0.5 on 2022-06-30 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_pig', '0003_alter_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birth',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 16, 58, 33, 401748)),
        ),
    ]
